CREATE TABLE IF NOT EXISTS PRODUCT(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    price DECIMAL(10,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    quantity INT
);

CREATE TABLE IF NOT EXISTS product_image(
    id SERIAL PRIMARY KEY,
    product_id INTEGER REFERENCES product(id),
    image TEXT
)