#scrape_configs:
#  - job_name: 'MyAppMetrics'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 3s
#    static_configs:
#      - targets: ['host.docker.internal:8080']
#        labels:
#          application: 'My Spring Boot Application'


global:
  scrape_interval: 60s
  evaluation_interval: 15s
  scrape_timeout: 30s

scrape_configs:
  # Monitorar o próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitorar serviços Spring Boot com Actuator
  - job_name: 'spring-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'gateway-service:8000'
          - 'product-service:8080'
          - 'order-service:8080'
          - 'user-service:8080'
        # Adicione outros serviços quando descomentar


  # Monitorar containers com cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

#  # Descoberta automática de serviços Docker
#  - job_name: 'docker-services'
#    docker_sd_configs:
#      - host: unix:///var/run/docker.sock
#        refresh_interval: 15s
#    relabel_configs:
#      - source_labels: [__meta_docker_container_label_prometheus_scrape]
#        action: keep
#        regex: true
#      - source_labels: [__meta_docker_container_label_prometheus_port]
#        action: replace
#        target_label: __address__
#        regex: (.+)
#        replacement: $1:${1}
#      - source_labels: [__meta_docker_container_label_prometheus_path]
#        action: replace
#        target_label: __metrics_path__
#        regex: (.+)
#      - source_labels: [__meta_docker_container_name]
#        action: replace
#        target_label: container